#!/bin/bash

### BEGIN INIT INFO
# Provides:          XrdTestHypervisor.py application instance
# Required-Start:    $all
# Required-Stop:     $all
# Defalt-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts instance of XrdTestSlave.py app
# Description:       starts instance of XrdTestSlave.py app using start-stop-daemon
### END INIT INFO

# Source Red Hat function library.
. /etc/rc.d/init.d/functions

RETVAL=0
DESC=XrdTestHypervisor.py
APP_PATH=/usr/sbin/
PYTHON=/usr/bin/python
OPTIONS=" -b "

PYTHON_LIBPATH=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`

start() {
        echo -n $"Starting $DESC: "
        
	cd $APP_PATH
	
	export PYTHONPATH=$PYTHON_LIBPATH/XrdTest
	$PYTHON $DESC $OPTIONS start
	RETVAL=$?
	return $RETVAL
}
stop() {
        echo -n $"Stopping $DESC: "

	cd $APP_PATH
	
export PYTHONPATH=$PYTHON_LIBPATH/XrdTest
	$PYTHON $DESC $OPTIONS stop
	echo
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        N=/etc/init.d/$DESC
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
